version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building React application...
      - npm run build

  post_build:
    commands:
      - echo Building Docker image...
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t atchayara/reactapp .
      - docker push atchayara/reactapp
